# Generated by fusen: do not edit by hand

#' Función para extraer colores de la dnmye como colores hex
#'
#' @param ... Nombre del color
#' @return
#' Paleta de colores institucionales para la República de Argentina
#' @export
#'
#' @examples

### Funcion
#' dnmye_colores()
#' 
#' dnmye_colores("rojo")
#' 
#' dnmye_colores(1)
dnmye_colores <- function(...) {
  
  ### Lista de colores de la dnmye
colores <- c(
  `rojo`         = "#EE3D8F",
  `naranja`      = "#F7941E",
  `amarillo`     = "#FFD100",
  `verde claro`  = "#D7DF23",
  `verde oscuro` = "#50B8B1",
  `violeta`      = "#9283BE",
  `celeste`      = "#37BBED",
  `gris oscuro`  = "#50535C",
  `gris medio`   = "#AAAAAA",
  `gris claro`   = "#E7E7E7")
  
  cols <- c(...)
  
  if (is.null(cols)) {
    return(unname(colores))
  }
  
  if (!is.null(cols) & is.character(cols)) {
    assertthat::assert_that(cols %in% c(names(colores)), 
                            msg = glue::glue("el valor debe encontrarse entre las siguientes opciones: {paste0(names(dnmye_colores), collapse = ', ')}"))
    
    return(unname(colores[cols]))
  }
  
  if (!is.null(cols) & is.numeric(cols)){
    
    assertthat::assert_that(unique(cols) %in% c(1:10), 
                            msg = glue::glue("Los valores numéricos van de 1 a {length(dnmye_colores)}"))
    
    return(unname(colores[cols]))
  }
}

#' Función para extraer colores de la dnmye como colores hex
#'
#' @param palette Nombre de la paleta de colores en dnmye_paletas. Se puede optar por *c2_continuo*, *c2_contraste* o *c10_todos*
#' @param reverse *TRUE* indica que la peleta debe ser invertida
#' @param ... Argumentos adicionales para definir con colorRampPalette()
#' @return
#' Paleta de colores institucionales para la República de Argentina
#' @export
#'
#' @examples

### Funcion
#' dnmye_paletas("c2_continuo")(3)
#' dnmye_paletas("c10_todos")(20)
dnmye_paletas <- function(palette = "c10_todos", reverse = FALSE, ...) {
  
  ### Paleta de colores
paletas <- list(
  
  `c2_continuo`  = c("#50B8B1", "#9283BE"),
  `c2_contraste` = c("#50B8B1", "#EE3D8F"),
  `c10_todos`     = c("#EE3D8F", "#F7941E", "#FFD100", "#D7DF23", "#50B8B1",
                      "#9283BE", "#37BBED", "#50535C", "#AAAAAA", "#E7E7E7"))

  pal <- paletas[[palette]]

  if (reverse) pal <- rev(pal)

  grDevices::colorRampPalette(pal, ...)
}

#' Constructor de escala de colores de contorno (color) para la dnmye
#'
#' @param palette Nombre de la paleta de colores en dnmye_paleta
#' @param discrete TRUE indica que la variable es discreta
#' @param reverse *TRUE* indica que la peleta debe ser invertida
#' @param ... Argumentos adicionales para definir en discrete_scale() o
#'            scale_color_gradientn(), respectivamente, cuando discrete es TRUE o FALSE
#' @export
#'
#' @examples

### Funcion
#' datafile <- system.file("toy_evyth.rds", package = "comunicacion")
#' toy_evyth <- readRDS(datafile)
#' 
#' toy_evyth %>% 
#'   dplyr::mutate(periodo = as.factor(paste0(anio, trimestre)),
#'                 region_destino = factor(region_destino, labels = c("Ciudad de Buenos Aires", "Provincia de Buenos Aires - Partidos del GBA",
#'                                                                    "Provincia de Buenos Aires - Resto", "Centro", "Litoral", "Norte", "Cuyo",
#'                                                                    "Patagonia"))) %>% 
#'   dplyr::group_by(periodo, region_destino) %>% 
#'   dplyr::summarise(cantidad_personas = sum(pondera)) %>% 
#'   ggplot2::ggplot(ggplot2::aes(x = periodo, y = cantidad_personas, colour = region_destino, group = region_destino)) +
#'   ggplot2::geom_line() +
#'   scale_colour_dnmye()
scale_colour_dnmye <- function(palette = "c10_todos", discrete = TRUE, reverse = FALSE, ...) {
  
  pal <- dnmye_paletas(palette = palette, reverse = reverse)

  if (discrete) {
    ggplot2::discrete_scale("colour", paste0("dnmye_", palette), palette = pal, ...)
  } else {
    ggplot2::scale_color_gradientn(colours = pal(256), ...)
  }
}

#' Constructor de escala de colores de contorno (color) para la dnmye
#'
#' @param palette Nombre de la paleta de colores en dnmye_paleta
#' @param discrete TRUE indica que la variable es discreta
#' @param reverse *TRUE* indica que la peleta debe ser invertida
#' @param ... Argumentos adicionales para definir en discrete_scale() o
#'            scale_color_gradientn(), respectivamente, cuando discrete es TRUE o FALSE
#' @export
#'
#' @examples

### Funcion
#' datafile <- system.file("toy_evyth.rds", package = "comunicacion")
#' toy_evyth <- readRDS(datafile)
#' 
#' toy_evyth %>% 
#'   dplyr::mutate(region_destino = factor(region_destino, labels = c("Ciudad de Buenos Aires", "Provincia de Buenos Aires - Partidos del GBA",
#'                                                                    "Provincia de Buenos Aires - Resto", "Centro", "Litoral", "Norte", "Cuyo",
#'                                                                    "Patagonia"))) %>% 
#'   dplyr::group_by(anio, region_destino) %>% 
#'   dplyr::summarise(cantidad_personas = sum(pondera)) %>% 
#'   ggplot2::ggplot(ggplot2::aes(x = anio, y = cantidad_personas, fill = region_destino)) +
#'   ggplot2::geom_col(position = ggplot2::position_dodge()) +
#'   scale_fill_dnmye()
scale_fill_dnmye <- function(palette = "c10_todos", discrete = TRUE, reverse = FALSE, ...) {
  
  pal <- dnmye_paletas(palette = palette, reverse = reverse)

  if (discrete) {
    ggplot2::discrete_scale("fill", paste0("dnmye_", palette), palette = pal, ...)
  } else {
    ggplot2::scale_fill_gradientn(colours = pal(256), ...)
  }
}
